In [1]:
%tensorflow_version 1.x
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout
from keras.optimizers import Adam
from tensorboardcolab import TensorBoardColab, TensorBoardColabCallback
from keras import backend as K
# tbc=TensorBoardColab()

TensorFlow 1.x selected.


Using TensorFlow backend.


In [14]:

model = Sequential()
#return_sequences: intermediate outputs of the LSTM cell is valid for the next layer.


# model = Sequential()

# model.add(Dense(100, input_dim = 999, activation ='tanh'))
# model.add(Dense(200, activation = 'tanh'))
# model.add(Dense(300, activation = 'tanh'))
# model.add(Dense(300, activation = 'relu'))
# model.add(Dense(1, activation = 'sigmoid'))

model.add(LSTM(20, input_shape = (999, 1), activation='tanh', return_sequences=True))
model.add(LSTM(40, activation='elu', return_sequences=True))
model.add(LSTM(50, activation='elu'))
model.add(Dense(1, activation = 'sigmoid'))

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 999, 20)           1760      
_________________________________________________________________
lstm_2 (LSTM)                (None, 999, 40)           9760      
_________________________________________________________________
lstm_3 (LSTM)                (None, 50)                18200     
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 51        
Total params: 29,771
Trainable params: 29,771
Non-trainable params: 0
_________________________________________________________________


In [0]:
labels = np.load("/content/drive/My Drive/Other/label_data.npy", allow_pickle=True)
sequences = np.load("/content/drive/My Drive/Other/sequences_data.npy", allow_pickle=True)

In [8]:


# for i in range(len(sequences[0])):
#   # sequences[i]
#   norm = np.linalg.norm(sequences[0][i])
#   sequences[0][i] = sequences[0][i]/norm

# print(sequences[0])

norm = np.linalg.norm(labels[0])
labels[0] = labels[0]/norm

x_train, y_train = sequences[0], labels[0][:sequences[0].shape[0]]
print(y_train, x_train[:10], y_train.shape)
x_train.shape

[0.00172915 0.00076502 0.00047019 ... 0.00067676 0.00172772 0.00175477] [[277120384 277120392 277120400 ... 277142032 277142040 277142048]
 [120215920 120215928 120215936 ... 122615528 122615536 122615544]
 [ 75352264  75352272  75352280 ...  75360216  75360224  75360232]
 ...
 [255873704 255873712 255873720 ... 255882016 255882024 255882032]
 [265572368 265572376 265572384 ... 265580544 265580552 265580560]
 [282643336 282643344 282643352 ... 277067848 277067856 277067864]] (462311,)


(462311, 999)

In [0]:
# opt = Adam(learning_rate = 0.0001, clipnorm = 1.0)

model.compile(optimizer="Adam", loss="binary_crossentropy", metrics = ['accuracy', percentage_difference])

In [0]:
def percentage_difference(y_true, y_pred):
    return abs(y_pred/y_true - 1)

In [17]:
x_train = x_train.reshape(x_train.shape[0], 999, 1)
model.fit(x_train, y_train, epochs=800)

Epoch 1/800
  2688/462311 [..............................] - ETA: 8:41:49 - loss: nan - accuracy: 0.0000e+00 - percentage_difference: 2625.1099

KeyboardInterrupt: ignored